In [2]:
import numpy as np

In [3]:
arr = np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr

array([[100, 200, 150, 300],
       [ 50,  60,  40,  80],
       [300, 400, 350, 500],
       [200, 250, 220, 270],
       [ 80,  90,  70, 100]])

In [6]:
#Determine the number of dimensions of the array.
arr.shape

(5, 4)

In [7]:

arr.dtype

dtype('int32')

In [8]:
#Identify the data type of elements in the array.
arr.size

20

In [9]:
#Find the total memory (in bytes) used by the array.
arr.nbytes

80

In [16]:
arr

array([[100, 200, 150, 300],
       [ 50,  60,  40,  80],
       [300, 400, 350, 500],
       [200, 250, 220, 270],
       [ 80,  90,  70, 100]])

In [17]:
#Add 20 units of stock to all products across all locations.
arr +=20

In [18]:
arr

array([[120, 220, 170, 320],
       [ 70,  80,  60, 100],
       [320, 420, 370, 520],
       [220, 270, 240, 290],
       [100, 110,  90, 120]])

In [19]:
#Deduct 10 units of stock from Product 3 across all locations.
arr[2] -=10

In [20]:
arr

array([[120, 220, 170, 320],
       [ 70,  80,  60, 100],
       [310, 410, 360, 510],
       [220, 270, 240, 290],
       [100, 110,  90, 120]])

In [21]:
#Double the stock of all products at Location 2 (column 2).
arr[:,1] *=2

In [22]:
arr

array([[120, 440, 170, 320],
       [ 70, 160,  60, 100],
       [310, 820, 360, 510],
       [220, 540, 240, 290],
       [100, 220,  90, 120]])

In [23]:
#Calculate the percentage of stock available for each product at all locations, 
#assuming the maximum capacity of each location is 1000 units.
max_cap=1000

percentage=(arr/max_cap)*100

In [24]:
arr

array([[120, 440, 170, 320],
       [ 70, 160,  60, 100],
       [310, 820, 360, 510],
       [220, 540, 240, 290],
       [100, 220,  90, 120]])

In [25]:
percentage

array([[12., 44., 17., 32.],
       [ 7., 16.,  6., 10.],
       [31., 82., 36., 51.],
       [22., 54., 24., 29.],
       [10., 22.,  9., 12.]])

In [33]:
arr

array([[120, 440, 170, 320],
       [ 70, 160,  60, 100],
       [310, 820, 360, 510],
       [220, 540, 240, 290],
       [100, 220,  90, 120]])

In [7]:
#Calculate the total stock of each product across all locations.
total=np.sum(arr,axis=1)
total

array([ 750,  230, 1550,  940,  340])

In [5]:
#Determine the total stock available in each location.
total_s=arr.sum(axis=0)
total_s

array([ 730, 1000,  830, 1250])

In [9]:
#Find the product with the maximum total stock across all locations.5 gtb   
max_product=total.argmax()
max_product=total[max_product]
max_product


1550

In [10]:
#Identify the location with the minimum total stock across all products.
min_location=total_s.argmin()
min_location=total_s[min_location]
min_location

730

In [11]:
#Compute the average stock per product across all locations.
avg_product=arr.mean(axis=1)
avg_product

array([187.5,  57.5, 387.5, 235. ,  85. ])

In [13]:
#Retrieve the stock levels of Product 2 across all locations.
productStock_2=arr[1,:]
productStock_2


array([50, 60, 40, 80])

In [14]:
#.Extract the stock levels for all products in Location 3.
locationStock_3=arr[:,2]
locationStock_3

array([150,  40, 350, 220,  70])

In [23]:
#Find the stock levels of Products 3 and 4 for Locations 2 and 4.
pro_loc=arr[2:4,[1,3]]
pro_loc

array([[400, 500],
       [250, 270]])

In [20]:
#.Extract the stock levels of the first 3 products for the first 2 locations.
pro_3Loc_2=arr[:3,:2]
pro_3Loc_2

array([[100, 200],
       [ 50,  60],
       [300, 400]])

In [24]:
#Slice the stock levels of the last 2 products for the last 2 locations.
pro_loc_last=arr[3:5,2:4]
pro_loc_last

array([[220, 270],
       [ 70, 100]])

In [25]:
#Identify the stock of Product 5 at Location 3.
pro_5loc_3=arr[4,2]
pro_5loc_3

70

In [26]:
#Use advanced indexing to find the stock levels of Product 1 at Location 1 and Product 4 at Location 3.
stock_level=arr[[0,3],[0,2]]
stock_level

array([100, 220])

In [27]:
#.Update the stock of Product 2 at Location 4 to 100 units.
arr[1,3]=100
arr

array([[100, 200, 150, 300],
       [ 50,  60,  40, 100],
       [300, 400, 350, 500],
       [200, 250, 220, 270],
       [ 80,  90,  70, 100]])